// SPDX-License-Identifier: AGPL-3.0-only

using System.Text.RegularExpressions;
using System.Xml.Linq;
using ArcForges.Build.Policy.Architecture;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ArcForges.ArcScope.ArchitectureTests;

/// <summary>
/// WP-05.03 for ArcScope. ArcScope owns no schema and generates no client: every wire type, service and client comes from
/// an exact published Contracts package. These checks keep it that way, and each has a negative fixture.
/// </summary>
internal static class ContractConsumptionChecks
{
    private static readonly Regex ExactVersion = new(@"^\d+\.\d+\.\d+(?:\.\d+)*(?:-[0-9A-Za-z]+(?:\.[0-9A-Za-z]+)*)?$", RegexOptions.CultureInvariant);

    // ---- Project level: how contracts are consumed -----------------------------------------------------------

    public static IReadOnlyList<string> FindProjectViolations(string root, string projectPath, XDocument project, XDocument packages)
    {
        var findings = new List<string>();
        string directory = System.IO.Path.GetDirectoryName(System.IO.Path.GetFullPath(System.IO.Path.Combine(root, projectPath)))!;
        string fullRoot = System.IO.Path.GetFullPath(root).TrimEnd(System.IO.Path.DirectorySeparatorChar) + System.IO.Path.DirectorySeparatorChar;
        foreach (var reference in project.Descendants("ProjectReference"))
        {
            string include = reference.Attribute("Include")?.Value.Replace('\\', '/') ?? "";
            string target = System.IO.Path.GetFullPath(System.IO.Path.Combine(directory, include));
            if (include.Length == 0 || !target.StartsWith(fullRoot, StringComparison.OrdinalIgnoreCase) || !File.Exists(target))
            {
                findings.Add($"{projectPath}: project reference leaves the owning repository or does not exist: {include}");
            }
        }

        foreach (var binary in project.Descendants("Reference").Where(element => element.Element("HintPath") is not null))
        {
            findings.Add($"{projectPath}: binary reference to {binary.Attribute("Include")?.Value}; contracts are consumed only as published packages");
        }

        foreach (var reference in project.Descendants("PackageReference"))
        {
            string id = reference.Attribute("Include")?.Value ?? reference.Attribute("Update")?.Value ?? "";
            bool inlineVersion = reference.Attribute("Version") is not null || reference.Attribute("VersionOverride") is not null
                || reference.Element("Version") is not null || reference.Element("VersionOverride") is not null;
            if (id.StartsWith("ArcForges.Contracts.", StringComparison.Ordinal) && inlineVersion)
            {
                findings.Add($"{projectPath}: contract package {id} bypasses its exact central pin");
            }

            if (id is "Grpc.Tools" or "Google.Protobuf.Tools" || id.StartsWith("Grpc.Tools.", StringComparison.Ordinal))
            {
                findings.Add($"{projectPath}: {id} would generate clients here; clients are generated by Contracts");
            }
        }

        foreach (var schema in project.Descendants().Where(element => element.Name.LocalName is "Protobuf" or "ProtoRoot"))
        {
            findings.Add($"{projectPath}: authored protobuf item {schema.Attribute("Include")?.Value}; schemas are owned by Contracts");
        }

        foreach (var version in packages.Descendants("PackageVersion"))
        {
            string id = version.Attribute("Include")?.Value ?? "";
            if (id.StartsWith("ArcForges.Contracts.", StringComparison.Ordinal)
                && !ExactVersion.IsMatch(version.Attribute("Version")?.Value ?? ""))
            {
                findings.Add($"Directory.Packages.props: contract package {id} is not an exact published version");
            }
        }

        return findings;
    }

    public static void VerifyRepository(string root)
    {
        var packages = XDocument.Load(System.IO.Path.Combine(root, "Directory.Packages.props"));
        var discovered = Directory.EnumerateFiles(root, "*.csproj", SearchOption.AllDirectories)
            .Select(path => System.IO.Path.GetRelativePath(root, path).Replace('\\', '/'))
            .Where(path => !path.Split('/').Any(part => part is "bin" or "obj" or ".worktree" or ".worktrees" or "artifacts" or "node_modules"))
            .Order(StringComparer.Ordinal).ToArray();
        var solution = XDocument.Load(System.IO.Path.Combine(root, "ArcScope.slnx"));
        var enrolled = solution.Descendants("Project").Select(project => project.Attribute("Path")!.Value)
            .Order(StringComparer.Ordinal).ToArray();
        Checks.SequenceEqual(enrolled, discovered, "A project is outside the solution or the solution lists a missing project.");
        foreach (string path in discovered)
        {
            Checks.Empty(FindProjectViolations(root, path, XDocument.Load(System.IO.Path.Combine(root, path)), packages),
                "A project consumes contracts other than as an exact published package.");
        }

        Checks.True(!File.Exists(System.IO.Path.Combine(root, ".gitmodules")), "A submodule or sibling source checkout would bypass the published contracts.");
        Checks.Empty(Directory.EnumerateFiles(root, "*.proto", SearchOption.AllDirectories)
            .Where(path => !System.IO.Path.GetRelativePath(root, path).Replace('\\', '/').Split('/')
                .Any(part => part is "bin" or "obj" or ".worktree" or ".worktrees" or "artifacts" or "node_modules")),
            "ArcScope holds an authored protobuf schema; schemas are owned by Contracts.");
        Checks.True(packages.Descendants("PackageVersion").Any(version => (version.Attribute("Include")?.Value ?? "").StartsWith("ArcForges.Contracts.", StringComparison.Ordinal)),
            "No exact contract pin was found; the consumption check has nothing to verify.");
    }

    // ---- Compilation level: how contracts are used by production code -----------------------------------------

    /// <summary>A production type implementing a protobuf message or deriving a gRPC client is hand-written wire code.</summary>
    public static IReadOnlyList<string> FindHandWrittenWireTypes(CSharpCompilation compilation)
    {
        var findings = new List<string>();
        foreach (var tree in compilation.SyntaxTrees)
        {
            var model = compilation.GetSemanticModel(tree);
            foreach (var declaration in tree.GetRoot().DescendantNodes().OfType<BaseTypeDeclarationSyntax>())
            {
                if (model.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type) continue;
                bool message = type.AllInterfaces.Any(contract =>
                    contract.OriginalDefinition.ToDisplayString().StartsWith("Google.Protobuf.IMessage", StringComparison.Ordinal));
                bool client = false;
                for (var current = type.BaseType; current is not null; current = current.BaseType)
                {
                    if (current.OriginalDefinition.ToDisplayString().StartsWith("Grpc.Core.ClientBase", StringComparison.Ordinal)) client = true;
                }

                if (message || client) findings.Add(declaration.GetLocation().ToString());
            }
        }

        return findings;
    }

    /// <summary>Hand-built method descriptors or marshallers bypass the generated service identity.</summary>
    public static IReadOnlyList<string> FindHandBuiltRpcDescriptors(CSharpCompilation compilation)
    {
        var findings = new List<string>();
        foreach (var tree in compilation.SyntaxTrees)
        {
            var model = compilation.GetSemanticModel(tree);
            foreach (var creation in tree.GetRoot().DescendantNodes().OfType<BaseObjectCreationExpressionSyntax>())
            {
                if (model.GetTypeInfo(creation).Type is { } created
                    && created.OriginalDefinition.ToDisplayString() is "Grpc.Core.Method<TRequest, TResponse>" or "Grpc.Core.Marshaller<T>")
                {
                    findings.Add(creation.GetLocation().ToString());
                }
            }

            foreach (var invocation in tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (model.GetSymbolInfo(invocation).Symbol is IMethodSymbol { Name: "Create", ContainingType: { } owner }
                    && owner.ToDisplayString() == "Grpc.Core.Marshallers")
                {
                    findings.Add(invocation.GetLocation().ToString());
                }
            }
        }

        return findings;
    }

    /// <summary>Public business clients use binary gRPC-Web; the text-encoded mode is never selected.</summary>
    public static IReadOnlyList<string> FindTextEncodedGrpcWeb(CSharpCompilation compilation)
    {
        var findings = new List<string>();
        foreach (var tree in compilation.SyntaxTrees)
        {
            var model = compilation.GetSemanticModel(tree);
            foreach (var access in tree.GetRoot().DescendantNodes().OfType<MemberAccessExpressionSyntax>())
            {
                if (model.GetSymbolInfo(access).Symbol is IFieldSymbol { Name: "GrpcWebText", ContainingType: { } owner }
                    && owner.ToDisplayString() == "Grpc.Net.Client.Web.GrpcWebMode")
                {
                    findings.Add(access.GetLocation().ToString());
                }
            }
        }

        return findings;
    }

    /// <summary>Serializer calls must bind compile-time JsonTypeInfo metadata; reflection serializers are unreachable.</summary>
    public static IReadOnlyList<string> FindUnregisteredJsonSerializer(Compilation compilation)
    {
        var findings = new List<string>();
        foreach (var tree in compilation.SyntaxTrees)
        {
            var model = compilation.GetSemanticModel(tree);
            foreach (var invocation in tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (model.GetSymbolInfo(invocation).Symbol is not IMethodSymbol method
                    || method.ContainingType.ToDisplayString() != "System.Text.Json.JsonSerializer") continue;
                bool hasTypeInfo = method.Parameters.Any(parameter =>
                    parameter.Type.OriginalDefinition.ToDisplayString().StartsWith("System.Text.Json.Serialization.Metadata.JsonTypeInfo", StringComparison.Ordinal));
                if (!hasTypeInfo) findings.Add(invocation.GetLocation().ToString());
            }
        }

        return findings;
    }

    /// <summary>Every consumption finding of one production compilation, as stable text.</summary>
    public static IReadOnlyList<string> FindAll(CSharpCompilation compilation) => FindHandWrittenWireTypes(compilation)
        .Concat(FindHandBuiltRpcDescriptors(compilation)).Concat(FindTextEncodedGrpcWeb(compilation))
        .Concat(FindUnregisteredJsonSerializer(compilation)).ToArray();

    /// <summary>The executable that hosts wire code must turn reflection-based JSON metadata off.</summary>
    public static bool DisablesReflectionJson(XDocument project) =>
        project.Descendants().Where(element => element.Name.LocalName == "JsonSerializerIsReflectionEnabledByDefault")
            .Select(element => element.Value).SequenceEqual(["false"]);

    // ---- Fixtures -------------------------------------------------------------------------------------------------

    private const string FakeWireTypes = """
        namespace Google.Protobuf { public interface IMessage { } public interface IMessage<T> : IMessage { } }
        namespace Grpc.Core
        {
            public abstract class ClientBase<T> { }
            public class Method<TRequest, TResponse> { }
            public class Marshaller<T> { }
            public static class Marshallers { public static Marshaller<T> Create<T>() => null!; }
        }
        namespace Grpc.Net.Client.Web { public enum GrpcWebMode { GrpcWeb, GrpcWebText } }
        """;

    public static void Fixtures()
    {
        CSharpCompilation Compile(string name, string source) => FixtureCompiler.Compile(name,
            new Dictionary<string, string> { ["fixture.cs"] = source, ["wire.cs"] = FakeWireTypes });

        var clean = Compile("Clean", "class Use { Grpc.Net.Client.Web.GrpcWebMode Mode => Grpc.Net.Client.Web.GrpcWebMode.GrpcWeb; }");
        Checks.Empty(FindHandWrittenWireTypes(clean).Concat(FindHandBuiltRpcDescriptors(clean)).Concat(FindTextEncodedGrpcWeb(clean)),
            "Generated-client consumption through binary gRPC-Web was rejected.");

        Checks.True(FindHandWrittenWireTypes(Compile("Message", "public sealed class Hand : Google.Protobuf.IMessage<Hand> { }")).Count != 0,
            "A hand-written protobuf message was accepted.");
        Checks.True(FindHandWrittenWireTypes(Compile("Client", "public sealed class Hand : Grpc.Core.ClientBase<Hand> { }")).Count != 0,
            "A hand-written gRPC client was accepted.");
        Checks.True(FindHandBuiltRpcDescriptors(Compile("Method", "class Use { object M() => new Grpc.Core.Method<int, int>(); }")).Count != 0,
            "A hand-built gRPC method descriptor was accepted.");
        Checks.True(FindHandBuiltRpcDescriptors(Compile("Marshaller", "class Use { object M() => Grpc.Core.Marshallers.Create<int>(); }")).Count != 0,
            "A hand-built gRPC marshaller was accepted.");
        Checks.True(FindTextEncodedGrpcWeb(Compile("Text", "class Use { object M() => Grpc.Net.Client.Web.GrpcWebMode.GrpcWebText; }")).Count != 0,
            "Text-encoded gRPC-Web was accepted.");

        const string registered = "using System.Text.Json; using System.Text.Json.Serialization.Metadata; record Wire { } class C { static JsonTypeInfo<Wire> Metadata => throw null!; static object? Read(string json) => JsonSerializer.Deserialize<Wire>(json, Metadata); }";
        const string reflective = "using System.Text.Json; record Wire { } class C { static object? Read(string json) => JsonSerializer.Deserialize<Wire>(json); }";
        Checks.Empty(FindUnregisteredJsonSerializer(Compile("Registered", registered)), "Registered compile-time JSON metadata was rejected.");
        Checks.True(FindUnregisteredJsonSerializer(Compile("Reflective", reflective)).Count != 0, "An unregistered reflection-serializer call was accepted.");

        Checks.True(DisablesReflectionJson(XDocument.Parse("<Project><PropertyGroup><JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault></PropertyGroup></Project>")),
            "A project that disables reflection JSON was rejected.");
        Checks.True(!DisablesReflectionJson(XDocument.Parse("<Project />")), "A project that leaves reflection JSON on was accepted.");
        Checks.True(!DisablesReflectionJson(XDocument.Parse("<Project><PropertyGroup><JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault></PropertyGroup></Project>")),
            "A project that enables reflection JSON was accepted.");

        string root = RepositoryRoot.Find();
        var packages = XDocument.Parse("<Project><ItemGroup><PackageVersion Include=\"ArcForges.Contracts.Foundation\" Version=\"1.0.0-ci.1.1\" /></ItemGroup></Project>");
        var goodProject = XDocument.Parse("<Project><ItemGroup><PackageReference Include=\"ArcForges.Contracts.Foundation\" /></ItemGroup></Project>");
        Checks.Empty(FindProjectViolations(root, "src/x/x.csproj", goodProject, packages), "A centrally pinned contract package was rejected.");
        foreach (string violation in new[]
        {
            "<ItemGroup><PackageReference Include=\"ArcForges.Contracts.Foundation\" Version=\"1.0.0\" /></ItemGroup>",
            "<ItemGroup><PackageReference Include=\"ArcForges.Contracts.Foundation\" VersionOverride=\"1.0.0\" /></ItemGroup>",
            "<ItemGroup><ProjectReference Include=\"../../../Contracts/src/Contracts.csproj\" /></ItemGroup>",
            "<ItemGroup><Reference Include=\"Contracts\"><HintPath>../lib/Contracts.dll</HintPath></Reference></ItemGroup>",
            "<ItemGroup><PackageReference Include=\"Grpc.Tools\" /></ItemGroup>",
            "<ItemGroup><Protobuf Include=\"hello.proto\" /></ItemGroup>",
        })
        {
            Checks.True(FindProjectViolations(root, "src/x/x.csproj", XDocument.Parse("<Project>" + violation + "</Project>"), packages).Count != 0,
                "A contract consumption violation was accepted: " + violation);
        }

        var floating = XDocument.Parse("<Project><ItemGroup><PackageVersion Include=\"ArcForges.Contracts.Foundation\" Version=\"1.0.*\" /></ItemGroup></Project>");
        Checks.True(FindProjectViolations(root, "src/x/x.csproj", goodProject, floating).Count != 0, "A floating contract pin was accepted.");
    }
}
